name: Download artifact
description: Download and extract an artifact(s)
author: aochmann
branding:
  icon: download
  color: blue
inputs:
  github_token:
    description: GitHub token
    required: false
    default: ${{github.token}}
  repo:
    description: Repository name with owner
    required: false
    default: ${{github.repository}}
  name:
    description: Artifact name (download all artifacts in not specified)
    required: false
  latest:
    description: Download latest artifact
    required: false
  path:
    description: Artifact unpack location
    required: false
    default: "./"
outputs:
  found-artifact:
    description: A boolean that indicates if the artifact was found.
  path:
    description: The path to the file or directory downloaded. If no artifact is found this will be an empty string.
runs:
  using: node16
  main: main.js
